# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /boot/system/bin/cmake

# The command to remove a file.
RM = /boot/system/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /boot/home/Develop/html-renderer/litehtml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /boot/home/Develop/html-renderer/litehtml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/boot/system/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/boot/system/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"libraries\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/boot/system/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/boot/system/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/boot/system/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/boot/system/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/boot/system/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/boot/system/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /boot/home/Develop/html-renderer/litehtml/CMakeFiles /boot/home/Develop/html-renderer/litehtml//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /boot/home/Develop/html-renderer/litehtml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named litehtml

# Build rule for target.
litehtml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 litehtml
.PHONY : litehtml

# fast build rule for target.
litehtml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/build
.PHONY : litehtml/fast

#=============================================================================
# Target rules for targets named gumbo

# Build rule for target.
gumbo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gumbo
.PHONY : gumbo

# fast build rule for target.
gumbo/fast:
	$(MAKE) $(MAKESILENT) -f src/gumbo/CMakeFiles/gumbo.dir/build.make src/gumbo/CMakeFiles/gumbo.dir/build
.PHONY : gumbo/fast

containers/haiku/container_haiku.o: containers/haiku/container_haiku.cpp.o
.PHONY : containers/haiku/container_haiku.o

# target to build an object file
containers/haiku/container_haiku.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/containers/haiku/container_haiku.cpp.o
.PHONY : containers/haiku/container_haiku.cpp.o

containers/haiku/container_haiku.i: containers/haiku/container_haiku.cpp.i
.PHONY : containers/haiku/container_haiku.i

# target to preprocess a source file
containers/haiku/container_haiku.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/containers/haiku/container_haiku.cpp.i
.PHONY : containers/haiku/container_haiku.cpp.i

containers/haiku/container_haiku.s: containers/haiku/container_haiku.cpp.s
.PHONY : containers/haiku/container_haiku.s

# target to generate assembly for a file
containers/haiku/container_haiku.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/containers/haiku/container_haiku.cpp.s
.PHONY : containers/haiku/container_haiku.cpp.s

src/background.o: src/background.cpp.o
.PHONY : src/background.o

# target to build an object file
src/background.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/background.cpp.o
.PHONY : src/background.cpp.o

src/background.i: src/background.cpp.i
.PHONY : src/background.i

# target to preprocess a source file
src/background.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/background.cpp.i
.PHONY : src/background.cpp.i

src/background.s: src/background.cpp.s
.PHONY : src/background.s

# target to generate assembly for a file
src/background.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/background.cpp.s
.PHONY : src/background.cpp.s

src/codepoint.o: src/codepoint.cpp.o
.PHONY : src/codepoint.o

# target to build an object file
src/codepoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/codepoint.cpp.o
.PHONY : src/codepoint.cpp.o

src/codepoint.i: src/codepoint.cpp.i
.PHONY : src/codepoint.i

# target to preprocess a source file
src/codepoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/codepoint.cpp.i
.PHONY : src/codepoint.cpp.i

src/codepoint.s: src/codepoint.cpp.s
.PHONY : src/codepoint.s

# target to generate assembly for a file
src/codepoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/codepoint.cpp.s
.PHONY : src/codepoint.cpp.s

src/css_borders.o: src/css_borders.cpp.o
.PHONY : src/css_borders.o

# target to build an object file
src/css_borders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_borders.cpp.o
.PHONY : src/css_borders.cpp.o

src/css_borders.i: src/css_borders.cpp.i
.PHONY : src/css_borders.i

# target to preprocess a source file
src/css_borders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_borders.cpp.i
.PHONY : src/css_borders.cpp.i

src/css_borders.s: src/css_borders.cpp.s
.PHONY : src/css_borders.s

# target to generate assembly for a file
src/css_borders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_borders.cpp.s
.PHONY : src/css_borders.cpp.s

src/css_length.o: src/css_length.cpp.o
.PHONY : src/css_length.o

# target to build an object file
src/css_length.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_length.cpp.o
.PHONY : src/css_length.cpp.o

src/css_length.i: src/css_length.cpp.i
.PHONY : src/css_length.i

# target to preprocess a source file
src/css_length.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_length.cpp.i
.PHONY : src/css_length.cpp.i

src/css_length.s: src/css_length.cpp.s
.PHONY : src/css_length.s

# target to generate assembly for a file
src/css_length.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_length.cpp.s
.PHONY : src/css_length.cpp.s

src/css_parser.o: src/css_parser.cpp.o
.PHONY : src/css_parser.o

# target to build an object file
src/css_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_parser.cpp.o
.PHONY : src/css_parser.cpp.o

src/css_parser.i: src/css_parser.cpp.i
.PHONY : src/css_parser.i

# target to preprocess a source file
src/css_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_parser.cpp.i
.PHONY : src/css_parser.cpp.i

src/css_parser.s: src/css_parser.cpp.s
.PHONY : src/css_parser.s

# target to generate assembly for a file
src/css_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_parser.cpp.s
.PHONY : src/css_parser.cpp.s

src/css_properties.o: src/css_properties.cpp.o
.PHONY : src/css_properties.o

# target to build an object file
src/css_properties.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_properties.cpp.o
.PHONY : src/css_properties.cpp.o

src/css_properties.i: src/css_properties.cpp.i
.PHONY : src/css_properties.i

# target to preprocess a source file
src/css_properties.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_properties.cpp.i
.PHONY : src/css_properties.cpp.i

src/css_properties.s: src/css_properties.cpp.s
.PHONY : src/css_properties.s

# target to generate assembly for a file
src/css_properties.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_properties.cpp.s
.PHONY : src/css_properties.cpp.s

src/css_selector.o: src/css_selector.cpp.o
.PHONY : src/css_selector.o

# target to build an object file
src/css_selector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_selector.cpp.o
.PHONY : src/css_selector.cpp.o

src/css_selector.i: src/css_selector.cpp.i
.PHONY : src/css_selector.i

# target to preprocess a source file
src/css_selector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_selector.cpp.i
.PHONY : src/css_selector.cpp.i

src/css_selector.s: src/css_selector.cpp.s
.PHONY : src/css_selector.s

# target to generate assembly for a file
src/css_selector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_selector.cpp.s
.PHONY : src/css_selector.cpp.s

src/css_tokenizer.o: src/css_tokenizer.cpp.o
.PHONY : src/css_tokenizer.o

# target to build an object file
src/css_tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_tokenizer.cpp.o
.PHONY : src/css_tokenizer.cpp.o

src/css_tokenizer.i: src/css_tokenizer.cpp.i
.PHONY : src/css_tokenizer.i

# target to preprocess a source file
src/css_tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_tokenizer.cpp.i
.PHONY : src/css_tokenizer.cpp.i

src/css_tokenizer.s: src/css_tokenizer.cpp.s
.PHONY : src/css_tokenizer.s

# target to generate assembly for a file
src/css_tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/css_tokenizer.cpp.s
.PHONY : src/css_tokenizer.cpp.s

src/document.o: src/document.cpp.o
.PHONY : src/document.o

# target to build an object file
src/document.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/document.cpp.o
.PHONY : src/document.cpp.o

src/document.i: src/document.cpp.i
.PHONY : src/document.i

# target to preprocess a source file
src/document.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/document.cpp.i
.PHONY : src/document.cpp.i

src/document.s: src/document.cpp.s
.PHONY : src/document.s

# target to generate assembly for a file
src/document.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/document.cpp.s
.PHONY : src/document.cpp.s

src/document_container.o: src/document_container.cpp.o
.PHONY : src/document_container.o

# target to build an object file
src/document_container.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/document_container.cpp.o
.PHONY : src/document_container.cpp.o

src/document_container.i: src/document_container.cpp.i
.PHONY : src/document_container.i

# target to preprocess a source file
src/document_container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/document_container.cpp.i
.PHONY : src/document_container.cpp.i

src/document_container.s: src/document_container.cpp.s
.PHONY : src/document_container.s

# target to generate assembly for a file
src/document_container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/document_container.cpp.s
.PHONY : src/document_container.cpp.s

src/el_anchor.o: src/el_anchor.cpp.o
.PHONY : src/el_anchor.o

# target to build an object file
src/el_anchor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_anchor.cpp.o
.PHONY : src/el_anchor.cpp.o

src/el_anchor.i: src/el_anchor.cpp.i
.PHONY : src/el_anchor.i

# target to preprocess a source file
src/el_anchor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_anchor.cpp.i
.PHONY : src/el_anchor.cpp.i

src/el_anchor.s: src/el_anchor.cpp.s
.PHONY : src/el_anchor.s

# target to generate assembly for a file
src/el_anchor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_anchor.cpp.s
.PHONY : src/el_anchor.cpp.s

src/el_base.o: src/el_base.cpp.o
.PHONY : src/el_base.o

# target to build an object file
src/el_base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_base.cpp.o
.PHONY : src/el_base.cpp.o

src/el_base.i: src/el_base.cpp.i
.PHONY : src/el_base.i

# target to preprocess a source file
src/el_base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_base.cpp.i
.PHONY : src/el_base.cpp.i

src/el_base.s: src/el_base.cpp.s
.PHONY : src/el_base.s

# target to generate assembly for a file
src/el_base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_base.cpp.s
.PHONY : src/el_base.cpp.s

src/el_before_after.o: src/el_before_after.cpp.o
.PHONY : src/el_before_after.o

# target to build an object file
src/el_before_after.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_before_after.cpp.o
.PHONY : src/el_before_after.cpp.o

src/el_before_after.i: src/el_before_after.cpp.i
.PHONY : src/el_before_after.i

# target to preprocess a source file
src/el_before_after.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_before_after.cpp.i
.PHONY : src/el_before_after.cpp.i

src/el_before_after.s: src/el_before_after.cpp.s
.PHONY : src/el_before_after.s

# target to generate assembly for a file
src/el_before_after.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_before_after.cpp.s
.PHONY : src/el_before_after.cpp.s

src/el_body.o: src/el_body.cpp.o
.PHONY : src/el_body.o

# target to build an object file
src/el_body.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_body.cpp.o
.PHONY : src/el_body.cpp.o

src/el_body.i: src/el_body.cpp.i
.PHONY : src/el_body.i

# target to preprocess a source file
src/el_body.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_body.cpp.i
.PHONY : src/el_body.cpp.i

src/el_body.s: src/el_body.cpp.s
.PHONY : src/el_body.s

# target to generate assembly for a file
src/el_body.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_body.cpp.s
.PHONY : src/el_body.cpp.s

src/el_break.o: src/el_break.cpp.o
.PHONY : src/el_break.o

# target to build an object file
src/el_break.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_break.cpp.o
.PHONY : src/el_break.cpp.o

src/el_break.i: src/el_break.cpp.i
.PHONY : src/el_break.i

# target to preprocess a source file
src/el_break.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_break.cpp.i
.PHONY : src/el_break.cpp.i

src/el_break.s: src/el_break.cpp.s
.PHONY : src/el_break.s

# target to generate assembly for a file
src/el_break.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_break.cpp.s
.PHONY : src/el_break.cpp.s

src/el_cdata.o: src/el_cdata.cpp.o
.PHONY : src/el_cdata.o

# target to build an object file
src/el_cdata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_cdata.cpp.o
.PHONY : src/el_cdata.cpp.o

src/el_cdata.i: src/el_cdata.cpp.i
.PHONY : src/el_cdata.i

# target to preprocess a source file
src/el_cdata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_cdata.cpp.i
.PHONY : src/el_cdata.cpp.i

src/el_cdata.s: src/el_cdata.cpp.s
.PHONY : src/el_cdata.s

# target to generate assembly for a file
src/el_cdata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_cdata.cpp.s
.PHONY : src/el_cdata.cpp.s

src/el_comment.o: src/el_comment.cpp.o
.PHONY : src/el_comment.o

# target to build an object file
src/el_comment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_comment.cpp.o
.PHONY : src/el_comment.cpp.o

src/el_comment.i: src/el_comment.cpp.i
.PHONY : src/el_comment.i

# target to preprocess a source file
src/el_comment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_comment.cpp.i
.PHONY : src/el_comment.cpp.i

src/el_comment.s: src/el_comment.cpp.s
.PHONY : src/el_comment.s

# target to generate assembly for a file
src/el_comment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_comment.cpp.s
.PHONY : src/el_comment.cpp.s

src/el_div.o: src/el_div.cpp.o
.PHONY : src/el_div.o

# target to build an object file
src/el_div.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_div.cpp.o
.PHONY : src/el_div.cpp.o

src/el_div.i: src/el_div.cpp.i
.PHONY : src/el_div.i

# target to preprocess a source file
src/el_div.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_div.cpp.i
.PHONY : src/el_div.cpp.i

src/el_div.s: src/el_div.cpp.s
.PHONY : src/el_div.s

# target to generate assembly for a file
src/el_div.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_div.cpp.s
.PHONY : src/el_div.cpp.s

src/el_font.o: src/el_font.cpp.o
.PHONY : src/el_font.o

# target to build an object file
src/el_font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_font.cpp.o
.PHONY : src/el_font.cpp.o

src/el_font.i: src/el_font.cpp.i
.PHONY : src/el_font.i

# target to preprocess a source file
src/el_font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_font.cpp.i
.PHONY : src/el_font.cpp.i

src/el_font.s: src/el_font.cpp.s
.PHONY : src/el_font.s

# target to generate assembly for a file
src/el_font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_font.cpp.s
.PHONY : src/el_font.cpp.s

src/el_image.o: src/el_image.cpp.o
.PHONY : src/el_image.o

# target to build an object file
src/el_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_image.cpp.o
.PHONY : src/el_image.cpp.o

src/el_image.i: src/el_image.cpp.i
.PHONY : src/el_image.i

# target to preprocess a source file
src/el_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_image.cpp.i
.PHONY : src/el_image.cpp.i

src/el_image.s: src/el_image.cpp.s
.PHONY : src/el_image.s

# target to generate assembly for a file
src/el_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_image.cpp.s
.PHONY : src/el_image.cpp.s

src/el_link.o: src/el_link.cpp.o
.PHONY : src/el_link.o

# target to build an object file
src/el_link.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_link.cpp.o
.PHONY : src/el_link.cpp.o

src/el_link.i: src/el_link.cpp.i
.PHONY : src/el_link.i

# target to preprocess a source file
src/el_link.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_link.cpp.i
.PHONY : src/el_link.cpp.i

src/el_link.s: src/el_link.cpp.s
.PHONY : src/el_link.s

# target to generate assembly for a file
src/el_link.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_link.cpp.s
.PHONY : src/el_link.cpp.s

src/el_para.o: src/el_para.cpp.o
.PHONY : src/el_para.o

# target to build an object file
src/el_para.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_para.cpp.o
.PHONY : src/el_para.cpp.o

src/el_para.i: src/el_para.cpp.i
.PHONY : src/el_para.i

# target to preprocess a source file
src/el_para.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_para.cpp.i
.PHONY : src/el_para.cpp.i

src/el_para.s: src/el_para.cpp.s
.PHONY : src/el_para.s

# target to generate assembly for a file
src/el_para.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_para.cpp.s
.PHONY : src/el_para.cpp.s

src/el_script.o: src/el_script.cpp.o
.PHONY : src/el_script.o

# target to build an object file
src/el_script.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_script.cpp.o
.PHONY : src/el_script.cpp.o

src/el_script.i: src/el_script.cpp.i
.PHONY : src/el_script.i

# target to preprocess a source file
src/el_script.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_script.cpp.i
.PHONY : src/el_script.cpp.i

src/el_script.s: src/el_script.cpp.s
.PHONY : src/el_script.s

# target to generate assembly for a file
src/el_script.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_script.cpp.s
.PHONY : src/el_script.cpp.s

src/el_space.o: src/el_space.cpp.o
.PHONY : src/el_space.o

# target to build an object file
src/el_space.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_space.cpp.o
.PHONY : src/el_space.cpp.o

src/el_space.i: src/el_space.cpp.i
.PHONY : src/el_space.i

# target to preprocess a source file
src/el_space.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_space.cpp.i
.PHONY : src/el_space.cpp.i

src/el_space.s: src/el_space.cpp.s
.PHONY : src/el_space.s

# target to generate assembly for a file
src/el_space.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_space.cpp.s
.PHONY : src/el_space.cpp.s

src/el_style.o: src/el_style.cpp.o
.PHONY : src/el_style.o

# target to build an object file
src/el_style.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_style.cpp.o
.PHONY : src/el_style.cpp.o

src/el_style.i: src/el_style.cpp.i
.PHONY : src/el_style.i

# target to preprocess a source file
src/el_style.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_style.cpp.i
.PHONY : src/el_style.cpp.i

src/el_style.s: src/el_style.cpp.s
.PHONY : src/el_style.s

# target to generate assembly for a file
src/el_style.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_style.cpp.s
.PHONY : src/el_style.cpp.s

src/el_table.o: src/el_table.cpp.o
.PHONY : src/el_table.o

# target to build an object file
src/el_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_table.cpp.o
.PHONY : src/el_table.cpp.o

src/el_table.i: src/el_table.cpp.i
.PHONY : src/el_table.i

# target to preprocess a source file
src/el_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_table.cpp.i
.PHONY : src/el_table.cpp.i

src/el_table.s: src/el_table.cpp.s
.PHONY : src/el_table.s

# target to generate assembly for a file
src/el_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_table.cpp.s
.PHONY : src/el_table.cpp.s

src/el_td.o: src/el_td.cpp.o
.PHONY : src/el_td.o

# target to build an object file
src/el_td.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_td.cpp.o
.PHONY : src/el_td.cpp.o

src/el_td.i: src/el_td.cpp.i
.PHONY : src/el_td.i

# target to preprocess a source file
src/el_td.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_td.cpp.i
.PHONY : src/el_td.cpp.i

src/el_td.s: src/el_td.cpp.s
.PHONY : src/el_td.s

# target to generate assembly for a file
src/el_td.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_td.cpp.s
.PHONY : src/el_td.cpp.s

src/el_text.o: src/el_text.cpp.o
.PHONY : src/el_text.o

# target to build an object file
src/el_text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_text.cpp.o
.PHONY : src/el_text.cpp.o

src/el_text.i: src/el_text.cpp.i
.PHONY : src/el_text.i

# target to preprocess a source file
src/el_text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_text.cpp.i
.PHONY : src/el_text.cpp.i

src/el_text.s: src/el_text.cpp.s
.PHONY : src/el_text.s

# target to generate assembly for a file
src/el_text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_text.cpp.s
.PHONY : src/el_text.cpp.s

src/el_title.o: src/el_title.cpp.o
.PHONY : src/el_title.o

# target to build an object file
src/el_title.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_title.cpp.o
.PHONY : src/el_title.cpp.o

src/el_title.i: src/el_title.cpp.i
.PHONY : src/el_title.i

# target to preprocess a source file
src/el_title.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_title.cpp.i
.PHONY : src/el_title.cpp.i

src/el_title.s: src/el_title.cpp.s
.PHONY : src/el_title.s

# target to generate assembly for a file
src/el_title.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_title.cpp.s
.PHONY : src/el_title.cpp.s

src/el_tr.o: src/el_tr.cpp.o
.PHONY : src/el_tr.o

# target to build an object file
src/el_tr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_tr.cpp.o
.PHONY : src/el_tr.cpp.o

src/el_tr.i: src/el_tr.cpp.i
.PHONY : src/el_tr.i

# target to preprocess a source file
src/el_tr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_tr.cpp.i
.PHONY : src/el_tr.cpp.i

src/el_tr.s: src/el_tr.cpp.s
.PHONY : src/el_tr.s

# target to generate assembly for a file
src/el_tr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/el_tr.cpp.s
.PHONY : src/el_tr.cpp.s

src/element.o: src/element.cpp.o
.PHONY : src/element.o

# target to build an object file
src/element.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/element.cpp.o
.PHONY : src/element.cpp.o

src/element.i: src/element.cpp.i
.PHONY : src/element.i

# target to preprocess a source file
src/element.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/element.cpp.i
.PHONY : src/element.cpp.i

src/element.s: src/element.cpp.s
.PHONY : src/element.s

# target to generate assembly for a file
src/element.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/element.cpp.s
.PHONY : src/element.cpp.s

src/encodings.o: src/encodings.cpp.o
.PHONY : src/encodings.o

# target to build an object file
src/encodings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/encodings.cpp.o
.PHONY : src/encodings.cpp.o

src/encodings.i: src/encodings.cpp.i
.PHONY : src/encodings.i

# target to preprocess a source file
src/encodings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/encodings.cpp.i
.PHONY : src/encodings.cpp.i

src/encodings.s: src/encodings.cpp.s
.PHONY : src/encodings.s

# target to generate assembly for a file
src/encodings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/encodings.cpp.s
.PHONY : src/encodings.cpp.s

src/flex_item.o: src/flex_item.cpp.o
.PHONY : src/flex_item.o

# target to build an object file
src/flex_item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/flex_item.cpp.o
.PHONY : src/flex_item.cpp.o

src/flex_item.i: src/flex_item.cpp.i
.PHONY : src/flex_item.i

# target to preprocess a source file
src/flex_item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/flex_item.cpp.i
.PHONY : src/flex_item.cpp.i

src/flex_item.s: src/flex_item.cpp.s
.PHONY : src/flex_item.s

# target to generate assembly for a file
src/flex_item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/flex_item.cpp.s
.PHONY : src/flex_item.cpp.s

src/flex_line.o: src/flex_line.cpp.o
.PHONY : src/flex_line.o

# target to build an object file
src/flex_line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/flex_line.cpp.o
.PHONY : src/flex_line.cpp.o

src/flex_line.i: src/flex_line.cpp.i
.PHONY : src/flex_line.i

# target to preprocess a source file
src/flex_line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/flex_line.cpp.i
.PHONY : src/flex_line.cpp.i

src/flex_line.s: src/flex_line.cpp.s
.PHONY : src/flex_line.s

# target to generate assembly for a file
src/flex_line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/flex_line.cpp.s
.PHONY : src/flex_line.cpp.s

src/formatting_context.o: src/formatting_context.cpp.o
.PHONY : src/formatting_context.o

# target to build an object file
src/formatting_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/formatting_context.cpp.o
.PHONY : src/formatting_context.cpp.o

src/formatting_context.i: src/formatting_context.cpp.i
.PHONY : src/formatting_context.i

# target to preprocess a source file
src/formatting_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/formatting_context.cpp.i
.PHONY : src/formatting_context.cpp.i

src/formatting_context.s: src/formatting_context.cpp.s
.PHONY : src/formatting_context.s

# target to generate assembly for a file
src/formatting_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/formatting_context.cpp.s
.PHONY : src/formatting_context.cpp.s

src/gradient.o: src/gradient.cpp.o
.PHONY : src/gradient.o

# target to build an object file
src/gradient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/gradient.cpp.o
.PHONY : src/gradient.cpp.o

src/gradient.i: src/gradient.cpp.i
.PHONY : src/gradient.i

# target to preprocess a source file
src/gradient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/gradient.cpp.i
.PHONY : src/gradient.cpp.i

src/gradient.s: src/gradient.cpp.s
.PHONY : src/gradient.s

# target to generate assembly for a file
src/gradient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/gradient.cpp.s
.PHONY : src/gradient.cpp.s

src/html.o: src/html.cpp.o
.PHONY : src/html.o

# target to build an object file
src/html.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/html.cpp.o
.PHONY : src/html.cpp.o

src/html.i: src/html.cpp.i
.PHONY : src/html.i

# target to preprocess a source file
src/html.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/html.cpp.i
.PHONY : src/html.cpp.i

src/html.s: src/html.cpp.s
.PHONY : src/html.s

# target to generate assembly for a file
src/html.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/html.cpp.s
.PHONY : src/html.cpp.s

src/html_microsyntaxes.o: src/html_microsyntaxes.cpp.o
.PHONY : src/html_microsyntaxes.o

# target to build an object file
src/html_microsyntaxes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/html_microsyntaxes.cpp.o
.PHONY : src/html_microsyntaxes.cpp.o

src/html_microsyntaxes.i: src/html_microsyntaxes.cpp.i
.PHONY : src/html_microsyntaxes.i

# target to preprocess a source file
src/html_microsyntaxes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/html_microsyntaxes.cpp.i
.PHONY : src/html_microsyntaxes.cpp.i

src/html_microsyntaxes.s: src/html_microsyntaxes.cpp.s
.PHONY : src/html_microsyntaxes.s

# target to generate assembly for a file
src/html_microsyntaxes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/html_microsyntaxes.cpp.s
.PHONY : src/html_microsyntaxes.cpp.s

src/html_tag.o: src/html_tag.cpp.o
.PHONY : src/html_tag.o

# target to build an object file
src/html_tag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/html_tag.cpp.o
.PHONY : src/html_tag.cpp.o

src/html_tag.i: src/html_tag.cpp.i
.PHONY : src/html_tag.i

# target to preprocess a source file
src/html_tag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/html_tag.cpp.i
.PHONY : src/html_tag.cpp.i

src/html_tag.s: src/html_tag.cpp.s
.PHONY : src/html_tag.s

# target to generate assembly for a file
src/html_tag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/html_tag.cpp.s
.PHONY : src/html_tag.cpp.s

src/iterators.o: src/iterators.cpp.o
.PHONY : src/iterators.o

# target to build an object file
src/iterators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/iterators.cpp.o
.PHONY : src/iterators.cpp.o

src/iterators.i: src/iterators.cpp.i
.PHONY : src/iterators.i

# target to preprocess a source file
src/iterators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/iterators.cpp.i
.PHONY : src/iterators.cpp.i

src/iterators.s: src/iterators.cpp.s
.PHONY : src/iterators.s

# target to generate assembly for a file
src/iterators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/iterators.cpp.s
.PHONY : src/iterators.cpp.s

src/line_box.o: src/line_box.cpp.o
.PHONY : src/line_box.o

# target to build an object file
src/line_box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/line_box.cpp.o
.PHONY : src/line_box.cpp.o

src/line_box.i: src/line_box.cpp.i
.PHONY : src/line_box.i

# target to preprocess a source file
src/line_box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/line_box.cpp.i
.PHONY : src/line_box.cpp.i

src/line_box.s: src/line_box.cpp.s
.PHONY : src/line_box.s

# target to generate assembly for a file
src/line_box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/line_box.cpp.s
.PHONY : src/line_box.cpp.s

src/media_query.o: src/media_query.cpp.o
.PHONY : src/media_query.o

# target to build an object file
src/media_query.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/media_query.cpp.o
.PHONY : src/media_query.cpp.o

src/media_query.i: src/media_query.cpp.i
.PHONY : src/media_query.i

# target to preprocess a source file
src/media_query.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/media_query.cpp.i
.PHONY : src/media_query.cpp.i

src/media_query.s: src/media_query.cpp.s
.PHONY : src/media_query.s

# target to generate assembly for a file
src/media_query.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/media_query.cpp.s
.PHONY : src/media_query.cpp.s

src/num_cvt.o: src/num_cvt.cpp.o
.PHONY : src/num_cvt.o

# target to build an object file
src/num_cvt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/num_cvt.cpp.o
.PHONY : src/num_cvt.cpp.o

src/num_cvt.i: src/num_cvt.cpp.i
.PHONY : src/num_cvt.i

# target to preprocess a source file
src/num_cvt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/num_cvt.cpp.i
.PHONY : src/num_cvt.cpp.i

src/num_cvt.s: src/num_cvt.cpp.s
.PHONY : src/num_cvt.s

# target to generate assembly for a file
src/num_cvt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/num_cvt.cpp.s
.PHONY : src/num_cvt.cpp.s

src/render_block.o: src/render_block.cpp.o
.PHONY : src/render_block.o

# target to build an object file
src/render_block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_block.cpp.o
.PHONY : src/render_block.cpp.o

src/render_block.i: src/render_block.cpp.i
.PHONY : src/render_block.i

# target to preprocess a source file
src/render_block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_block.cpp.i
.PHONY : src/render_block.cpp.i

src/render_block.s: src/render_block.cpp.s
.PHONY : src/render_block.s

# target to generate assembly for a file
src/render_block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_block.cpp.s
.PHONY : src/render_block.cpp.s

src/render_block_context.o: src/render_block_context.cpp.o
.PHONY : src/render_block_context.o

# target to build an object file
src/render_block_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_block_context.cpp.o
.PHONY : src/render_block_context.cpp.o

src/render_block_context.i: src/render_block_context.cpp.i
.PHONY : src/render_block_context.i

# target to preprocess a source file
src/render_block_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_block_context.cpp.i
.PHONY : src/render_block_context.cpp.i

src/render_block_context.s: src/render_block_context.cpp.s
.PHONY : src/render_block_context.s

# target to generate assembly for a file
src/render_block_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_block_context.cpp.s
.PHONY : src/render_block_context.cpp.s

src/render_flex.o: src/render_flex.cpp.o
.PHONY : src/render_flex.o

# target to build an object file
src/render_flex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_flex.cpp.o
.PHONY : src/render_flex.cpp.o

src/render_flex.i: src/render_flex.cpp.i
.PHONY : src/render_flex.i

# target to preprocess a source file
src/render_flex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_flex.cpp.i
.PHONY : src/render_flex.cpp.i

src/render_flex.s: src/render_flex.cpp.s
.PHONY : src/render_flex.s

# target to generate assembly for a file
src/render_flex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_flex.cpp.s
.PHONY : src/render_flex.cpp.s

src/render_image.o: src/render_image.cpp.o
.PHONY : src/render_image.o

# target to build an object file
src/render_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_image.cpp.o
.PHONY : src/render_image.cpp.o

src/render_image.i: src/render_image.cpp.i
.PHONY : src/render_image.i

# target to preprocess a source file
src/render_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_image.cpp.i
.PHONY : src/render_image.cpp.i

src/render_image.s: src/render_image.cpp.s
.PHONY : src/render_image.s

# target to generate assembly for a file
src/render_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_image.cpp.s
.PHONY : src/render_image.cpp.s

src/render_inline_context.o: src/render_inline_context.cpp.o
.PHONY : src/render_inline_context.o

# target to build an object file
src/render_inline_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_inline_context.cpp.o
.PHONY : src/render_inline_context.cpp.o

src/render_inline_context.i: src/render_inline_context.cpp.i
.PHONY : src/render_inline_context.i

# target to preprocess a source file
src/render_inline_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_inline_context.cpp.i
.PHONY : src/render_inline_context.cpp.i

src/render_inline_context.s: src/render_inline_context.cpp.s
.PHONY : src/render_inline_context.s

# target to generate assembly for a file
src/render_inline_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_inline_context.cpp.s
.PHONY : src/render_inline_context.cpp.s

src/render_item.o: src/render_item.cpp.o
.PHONY : src/render_item.o

# target to build an object file
src/render_item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_item.cpp.o
.PHONY : src/render_item.cpp.o

src/render_item.i: src/render_item.cpp.i
.PHONY : src/render_item.i

# target to preprocess a source file
src/render_item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_item.cpp.i
.PHONY : src/render_item.cpp.i

src/render_item.s: src/render_item.cpp.s
.PHONY : src/render_item.s

# target to generate assembly for a file
src/render_item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_item.cpp.s
.PHONY : src/render_item.cpp.s

src/render_table.o: src/render_table.cpp.o
.PHONY : src/render_table.o

# target to build an object file
src/render_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_table.cpp.o
.PHONY : src/render_table.cpp.o

src/render_table.i: src/render_table.cpp.i
.PHONY : src/render_table.i

# target to preprocess a source file
src/render_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_table.cpp.i
.PHONY : src/render_table.cpp.i

src/render_table.s: src/render_table.cpp.s
.PHONY : src/render_table.s

# target to generate assembly for a file
src/render_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/render_table.cpp.s
.PHONY : src/render_table.cpp.s

src/string_id.o: src/string_id.cpp.o
.PHONY : src/string_id.o

# target to build an object file
src/string_id.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/string_id.cpp.o
.PHONY : src/string_id.cpp.o

src/string_id.i: src/string_id.cpp.i
.PHONY : src/string_id.i

# target to preprocess a source file
src/string_id.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/string_id.cpp.i
.PHONY : src/string_id.cpp.i

src/string_id.s: src/string_id.cpp.s
.PHONY : src/string_id.s

# target to generate assembly for a file
src/string_id.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/string_id.cpp.s
.PHONY : src/string_id.cpp.s

src/strtod.o: src/strtod.cpp.o
.PHONY : src/strtod.o

# target to build an object file
src/strtod.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/strtod.cpp.o
.PHONY : src/strtod.cpp.o

src/strtod.i: src/strtod.cpp.i
.PHONY : src/strtod.i

# target to preprocess a source file
src/strtod.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/strtod.cpp.i
.PHONY : src/strtod.cpp.i

src/strtod.s: src/strtod.cpp.s
.PHONY : src/strtod.s

# target to generate assembly for a file
src/strtod.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/strtod.cpp.s
.PHONY : src/strtod.cpp.s

src/style.o: src/style.cpp.o
.PHONY : src/style.o

# target to build an object file
src/style.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/style.cpp.o
.PHONY : src/style.cpp.o

src/style.i: src/style.cpp.i
.PHONY : src/style.i

# target to preprocess a source file
src/style.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/style.cpp.i
.PHONY : src/style.cpp.i

src/style.s: src/style.cpp.s
.PHONY : src/style.s

# target to generate assembly for a file
src/style.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/style.cpp.s
.PHONY : src/style.cpp.s

src/stylesheet.o: src/stylesheet.cpp.o
.PHONY : src/stylesheet.o

# target to build an object file
src/stylesheet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/stylesheet.cpp.o
.PHONY : src/stylesheet.cpp.o

src/stylesheet.i: src/stylesheet.cpp.i
.PHONY : src/stylesheet.i

# target to preprocess a source file
src/stylesheet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/stylesheet.cpp.i
.PHONY : src/stylesheet.cpp.i

src/stylesheet.s: src/stylesheet.cpp.s
.PHONY : src/stylesheet.s

# target to generate assembly for a file
src/stylesheet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/stylesheet.cpp.s
.PHONY : src/stylesheet.cpp.s

src/table.o: src/table.cpp.o
.PHONY : src/table.o

# target to build an object file
src/table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/table.cpp.o
.PHONY : src/table.cpp.o

src/table.i: src/table.cpp.i
.PHONY : src/table.i

# target to preprocess a source file
src/table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/table.cpp.i
.PHONY : src/table.cpp.i

src/table.s: src/table.cpp.s
.PHONY : src/table.s

# target to generate assembly for a file
src/table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/table.cpp.s
.PHONY : src/table.cpp.s

src/tstring_view.o: src/tstring_view.cpp.o
.PHONY : src/tstring_view.o

# target to build an object file
src/tstring_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/tstring_view.cpp.o
.PHONY : src/tstring_view.cpp.o

src/tstring_view.i: src/tstring_view.cpp.i
.PHONY : src/tstring_view.i

# target to preprocess a source file
src/tstring_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/tstring_view.cpp.i
.PHONY : src/tstring_view.cpp.i

src/tstring_view.s: src/tstring_view.cpp.s
.PHONY : src/tstring_view.s

# target to generate assembly for a file
src/tstring_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/tstring_view.cpp.s
.PHONY : src/tstring_view.cpp.s

src/url.o: src/url.cpp.o
.PHONY : src/url.o

# target to build an object file
src/url.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/url.cpp.o
.PHONY : src/url.cpp.o

src/url.i: src/url.cpp.i
.PHONY : src/url.i

# target to preprocess a source file
src/url.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/url.cpp.i
.PHONY : src/url.cpp.i

src/url.s: src/url.cpp.s
.PHONY : src/url.s

# target to generate assembly for a file
src/url.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/url.cpp.s
.PHONY : src/url.cpp.s

src/url_path.o: src/url_path.cpp.o
.PHONY : src/url_path.o

# target to build an object file
src/url_path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/url_path.cpp.o
.PHONY : src/url_path.cpp.o

src/url_path.i: src/url_path.cpp.i
.PHONY : src/url_path.i

# target to preprocess a source file
src/url_path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/url_path.cpp.i
.PHONY : src/url_path.cpp.i

src/url_path.s: src/url_path.cpp.s
.PHONY : src/url_path.s

# target to generate assembly for a file
src/url_path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/url_path.cpp.s
.PHONY : src/url_path.cpp.s

src/utf8_strings.o: src/utf8_strings.cpp.o
.PHONY : src/utf8_strings.o

# target to build an object file
src/utf8_strings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/utf8_strings.cpp.o
.PHONY : src/utf8_strings.cpp.o

src/utf8_strings.i: src/utf8_strings.cpp.i
.PHONY : src/utf8_strings.i

# target to preprocess a source file
src/utf8_strings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/utf8_strings.cpp.i
.PHONY : src/utf8_strings.cpp.i

src/utf8_strings.s: src/utf8_strings.cpp.s
.PHONY : src/utf8_strings.s

# target to generate assembly for a file
src/utf8_strings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/utf8_strings.cpp.s
.PHONY : src/utf8_strings.cpp.s

src/web_color.o: src/web_color.cpp.o
.PHONY : src/web_color.o

# target to build an object file
src/web_color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/web_color.cpp.o
.PHONY : src/web_color.cpp.o

src/web_color.i: src/web_color.cpp.i
.PHONY : src/web_color.i

# target to preprocess a source file
src/web_color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/web_color.cpp.i
.PHONY : src/web_color.cpp.i

src/web_color.s: src/web_color.cpp.s
.PHONY : src/web_color.s

# target to generate assembly for a file
src/web_color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/litehtml.dir/build.make CMakeFiles/litehtml.dir/src/web_color.cpp.s
.PHONY : src/web_color.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gumbo"
	@echo "... litehtml"
	@echo "... containers/haiku/container_haiku.o"
	@echo "... containers/haiku/container_haiku.i"
	@echo "... containers/haiku/container_haiku.s"
	@echo "... src/background.o"
	@echo "... src/background.i"
	@echo "... src/background.s"
	@echo "... src/codepoint.o"
	@echo "... src/codepoint.i"
	@echo "... src/codepoint.s"
	@echo "... src/css_borders.o"
	@echo "... src/css_borders.i"
	@echo "... src/css_borders.s"
	@echo "... src/css_length.o"
	@echo "... src/css_length.i"
	@echo "... src/css_length.s"
	@echo "... src/css_parser.o"
	@echo "... src/css_parser.i"
	@echo "... src/css_parser.s"
	@echo "... src/css_properties.o"
	@echo "... src/css_properties.i"
	@echo "... src/css_properties.s"
	@echo "... src/css_selector.o"
	@echo "... src/css_selector.i"
	@echo "... src/css_selector.s"
	@echo "... src/css_tokenizer.o"
	@echo "... src/css_tokenizer.i"
	@echo "... src/css_tokenizer.s"
	@echo "... src/document.o"
	@echo "... src/document.i"
	@echo "... src/document.s"
	@echo "... src/document_container.o"
	@echo "... src/document_container.i"
	@echo "... src/document_container.s"
	@echo "... src/el_anchor.o"
	@echo "... src/el_anchor.i"
	@echo "... src/el_anchor.s"
	@echo "... src/el_base.o"
	@echo "... src/el_base.i"
	@echo "... src/el_base.s"
	@echo "... src/el_before_after.o"
	@echo "... src/el_before_after.i"
	@echo "... src/el_before_after.s"
	@echo "... src/el_body.o"
	@echo "... src/el_body.i"
	@echo "... src/el_body.s"
	@echo "... src/el_break.o"
	@echo "... src/el_break.i"
	@echo "... src/el_break.s"
	@echo "... src/el_cdata.o"
	@echo "... src/el_cdata.i"
	@echo "... src/el_cdata.s"
	@echo "... src/el_comment.o"
	@echo "... src/el_comment.i"
	@echo "... src/el_comment.s"
	@echo "... src/el_div.o"
	@echo "... src/el_div.i"
	@echo "... src/el_div.s"
	@echo "... src/el_font.o"
	@echo "... src/el_font.i"
	@echo "... src/el_font.s"
	@echo "... src/el_image.o"
	@echo "... src/el_image.i"
	@echo "... src/el_image.s"
	@echo "... src/el_link.o"
	@echo "... src/el_link.i"
	@echo "... src/el_link.s"
	@echo "... src/el_para.o"
	@echo "... src/el_para.i"
	@echo "... src/el_para.s"
	@echo "... src/el_script.o"
	@echo "... src/el_script.i"
	@echo "... src/el_script.s"
	@echo "... src/el_space.o"
	@echo "... src/el_space.i"
	@echo "... src/el_space.s"
	@echo "... src/el_style.o"
	@echo "... src/el_style.i"
	@echo "... src/el_style.s"
	@echo "... src/el_table.o"
	@echo "... src/el_table.i"
	@echo "... src/el_table.s"
	@echo "... src/el_td.o"
	@echo "... src/el_td.i"
	@echo "... src/el_td.s"
	@echo "... src/el_text.o"
	@echo "... src/el_text.i"
	@echo "... src/el_text.s"
	@echo "... src/el_title.o"
	@echo "... src/el_title.i"
	@echo "... src/el_title.s"
	@echo "... src/el_tr.o"
	@echo "... src/el_tr.i"
	@echo "... src/el_tr.s"
	@echo "... src/element.o"
	@echo "... src/element.i"
	@echo "... src/element.s"
	@echo "... src/encodings.o"
	@echo "... src/encodings.i"
	@echo "... src/encodings.s"
	@echo "... src/flex_item.o"
	@echo "... src/flex_item.i"
	@echo "... src/flex_item.s"
	@echo "... src/flex_line.o"
	@echo "... src/flex_line.i"
	@echo "... src/flex_line.s"
	@echo "... src/formatting_context.o"
	@echo "... src/formatting_context.i"
	@echo "... src/formatting_context.s"
	@echo "... src/gradient.o"
	@echo "... src/gradient.i"
	@echo "... src/gradient.s"
	@echo "... src/html.o"
	@echo "... src/html.i"
	@echo "... src/html.s"
	@echo "... src/html_microsyntaxes.o"
	@echo "... src/html_microsyntaxes.i"
	@echo "... src/html_microsyntaxes.s"
	@echo "... src/html_tag.o"
	@echo "... src/html_tag.i"
	@echo "... src/html_tag.s"
	@echo "... src/iterators.o"
	@echo "... src/iterators.i"
	@echo "... src/iterators.s"
	@echo "... src/line_box.o"
	@echo "... src/line_box.i"
	@echo "... src/line_box.s"
	@echo "... src/media_query.o"
	@echo "... src/media_query.i"
	@echo "... src/media_query.s"
	@echo "... src/num_cvt.o"
	@echo "... src/num_cvt.i"
	@echo "... src/num_cvt.s"
	@echo "... src/render_block.o"
	@echo "... src/render_block.i"
	@echo "... src/render_block.s"
	@echo "... src/render_block_context.o"
	@echo "... src/render_block_context.i"
	@echo "... src/render_block_context.s"
	@echo "... src/render_flex.o"
	@echo "... src/render_flex.i"
	@echo "... src/render_flex.s"
	@echo "... src/render_image.o"
	@echo "... src/render_image.i"
	@echo "... src/render_image.s"
	@echo "... src/render_inline_context.o"
	@echo "... src/render_inline_context.i"
	@echo "... src/render_inline_context.s"
	@echo "... src/render_item.o"
	@echo "... src/render_item.i"
	@echo "... src/render_item.s"
	@echo "... src/render_table.o"
	@echo "... src/render_table.i"
	@echo "... src/render_table.s"
	@echo "... src/string_id.o"
	@echo "... src/string_id.i"
	@echo "... src/string_id.s"
	@echo "... src/strtod.o"
	@echo "... src/strtod.i"
	@echo "... src/strtod.s"
	@echo "... src/style.o"
	@echo "... src/style.i"
	@echo "... src/style.s"
	@echo "... src/stylesheet.o"
	@echo "... src/stylesheet.i"
	@echo "... src/stylesheet.s"
	@echo "... src/table.o"
	@echo "... src/table.i"
	@echo "... src/table.s"
	@echo "... src/tstring_view.o"
	@echo "... src/tstring_view.i"
	@echo "... src/tstring_view.s"
	@echo "... src/url.o"
	@echo "... src/url.i"
	@echo "... src/url.s"
	@echo "... src/url_path.o"
	@echo "... src/url_path.i"
	@echo "... src/url_path.s"
	@echo "... src/utf8_strings.o"
	@echo "... src/utf8_strings.i"
	@echo "... src/utf8_strings.s"
	@echo "... src/web_color.o"
	@echo "... src/web_color.i"
	@echo "... src/web_color.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

